### ISSUE TITLE
Can't add orbit-core to yarn project. 

### ISSUE THREAD

**Issue by taarushv** [orbitdb/orbit-core#17]
`yarn add orbit_` returns: 
```
yarn add v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error orbit-db@0.17.3: The engine "node" is incompatible with this module. Expected version "^6.x.x". Got "11.9.0
"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

`yarn add orbit_ --ignore-engines` seems to be a workaround.

**Comment by RichardLitt** [comment]
@JaniAnttonen 	Does that sound right, to you?

**Comment by JaniAnttonen** [comment]
Since this project is still under a heavy refactoring, the master is unfortunately out-of-date. For the time being, I recommend using the branch `dev/overall-refactor`. It should be able to merge to master soon, since orbit-web already works with it.

**Comment by latenssi** [comment]
This is now fixed in current master
