### ISSUE TITLE
RFI: Distributed Nodes

### ISSUE THREAD

**Issue by zoernert** [orbitdb/orbit-core#5]
Using orbit-core (as chat) - is it possible to join on the same channel from different nodes? By sharing usernames key? 

I try to abstract from orbitdb-db and orbit_  on how ipfs p2p is used in orbitdb.

Thanks, 
Thorsten

**Comment by haadcode** [comment]
> is it possible to join on the same channel from different nodes? By sharing usernames key?

It is possible to join a channel from different nodes. This can be either by using unique usernames or by using same usernames. The usernames are not unique, but each username has a signing attached to it which is unique per node per username (per origin in the browser).

> I try to abstract from orbitdb-db and orbit_ on how ipfs p2p is used in orbitdb.

"IPFS p2p" in terms of networking is all handled by IPFS. orbit(-db) uses `ipfs.object.put` and `ipfs.object.get` features to persist the data. Whenever a database (in Orbit chat's case, the messages in the channel) is updated, orbit-db sends a messages to an [IPFS Pubsub](https://github.com/ipfs/js-ipfs#pubsub) topic (which is currently the channel name) and peers who are subscribed to that topic will receive the message. The receiving peers will then use IPFS (object.get) to fetch the data (ie. the blocks) from the IPFS network as they would fetch any other hash.

Does that answer your question @zoernert? Let me know if I can help further.

**Comment by zoernert** [comment]
Yes thanks! - After fixing my PubSub I was able to reproduce the architecture so that it works.

**Comment by haadcode** [comment]
Great to hear! Please do open issues in the future for any further questions.
